#📸 Face Image Recording, Training, and Attendance System

This repository contains a complete Python project for collecting facial image data, training a face recognition model, and utilizing it for applications like automated attendance tracking, all wrapped in a Graphical User Interface (GUI).

The project leverages the power of **OpenCV** for camera interaction and image processing, and **MediaPipe** for high-accuracy face detection and landmark tracking, ensuring high-quality, aligned data for machine learning tasks.

## 🌟 Features

* **Robust Data Collection:** Records cropped and eye-aligned face images, along with rich metadata and raw MediaPipe landmarks.
* **Face Alignment:** Automatically rotates and scales captured faces so that the eyes are consistently horizontal, significantly improving data quality for model training.
* **Model Training:** Dedicated script (`face_trainer.py`) for training a face recognition model on the collected dataset.
* **Real-time Recognition:** Script (`face_recognizer.py`) for live face detection and identification.
* **Attendance Tracking:** Outputs a log (`attendance.csv`/`.xlsx`) for recognized individuals.
* **Graphical User Interface (GUI):** A user-friendly interface (`gui.py`) to manage all main functions.

## 🛠️ Prerequisites

Before running any script, ensure you have Python (version 3.7+) installed.

### 1. Installation

It is highly recommended to use a virtual environment to manage dependencies.

```bash
# 1. Create a virtual environment (optional but recommended)
python -m venv venv

# 2. Activate the environment
# On Windows:
.\venv\Scripts\activate
# On macOS/Linux:
source venv/bin/activate

# 3. Install the required packages
pip install opencv-python mediapipe numpy pandas
🚀 UsageThe repository contains several key scripts for the full workflow:A. Data Recording (face_data_recorder.py)This is the primary script for capturing your face data.Bashpython face_data_recorder.py
Controls and InteractionOnce the camera window opens, use the following keyboard shortcuts to control the recording process:KeyActionDescriptionnSet Label/Name(MANDATORY FIRST STEP) Prompts you in the terminal to enter a unique label (e.g., user_john or person_ID_101). This creates the storage folder for the data.sToggle SavingStarts or stops the automatic continuous saving of face images. Data is typically saved every 1 frame.cToggle Center-OnlyWhen enabled, only saves faces that are near the center of the camera frame, ensuring better framing.lToggle LandmarksShows or hides the MediaPipe Face Mesh landmarks overlay on the live feed.mToggle Use MeshToggles the use of the Face Mesh model (required for eye-based alignment).qQuit & FinalizeCloses the camera and writes the final manifest files (manifest.csv and manifest.json).B. Model Training (face_trainer.py)After collecting a dataset using the recorder, run the trainer script to generate the recognition model.Bashpython face_trainer.py
This script will process the images in your dataset/ folder and save the trained model weights into the trainer/ directory.C. Face Recognition and Attendance (face_recognizer.py)Run this script to open the camera, load the trained model, and begin recognizing faces in real-time.Bashpython face_recognizer.py
The script will use the saved model to identify individuals and log their presence in the attendance.csv and attendance.xlsx files.D. Graphical User Interface (gui.py)Use the main GUI script for a unified experience, providing buttons and controls for all major functions (Recording, Training, Recognition).Bashpython gui.py
📁 Output Data StructureThe data recorder script automatically creates a root folder named dataset and organizes the captured data within it:.
├── dataset/
│   ├── [your_label_name]/
│   │   ├── image_filename.jpg                 (Aligned face image)
│   │   ├── image_filename.json                (Per-image metadata: bbox, score, etc.)
│   │   └── image_filename.landmarks.json      (Raw MediaPipe landmarks)
│   ├── manifest.csv                           (CSV summary of all recorded data)
│   └── manifest.json                          (JSON array of all recorded metadata)
├── trainer/
│   └── (trained model weights/files)          (Generated by face_trainer.py)
├── attendance.csv                             (Attendance log output)
└── ...
📝 Script Overviewface_data_recorder.py: The main script for capturing high-quality, aligned facial data.face_trainer.py: Handles the process of reading the collected data and training a recognition model.face_recognizer.py: Implements real-time face detection, recognition, and attendance logging using the trained model.gui.py: Provides a simple Tkinter/PyQt interface (depending on implementation) to manage the workflow.face.py (Simple Cropping): (If present) A simplified example for basic, unaligned face detection and cropping, useful for quick testing.
